export default {
    crushMasterTask:{
        "code": 200,
        "data": {
            "list": [
                {
                "parentTask": {
                "taskId": 251,
                "taskName": "任务线一3.0",
                "gameType": 0,
                "taskDesc": "任务线一3.0888金叶子",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 1,
                "taskLogId": 890834,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "888金叶子",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/cdn/platform/task/festival/sj-leaf.png",
                "taskDescShow": "任务线一3.0",
                "awardsNum": 0,
                "taskType": 10,
                "subTask": "248,250",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 21,
                "sort": 1
                },
                "subListA": [
                {
                "taskId": 246,
                "taskName": "任务线一1.1",
                "gameType": 12,
                "taskDesc": "任务线一1.1500000金叶子",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 2,
                "taskLogId": 890830,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "500000金叶子",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/12/DF/CmcEHVv7j9CAacFqAAAi8QULDxM815.png",
                "taskDescShow": "任务线一1.1",
                "awardsNum": 500000,
                "taskType": 8,
                "subTask": "",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 1
                },
                {
                "taskId": 247,
                "taskName": "任务线一1.2",
                "gameType": 12,
                "taskDesc": "任务线一1.2伊豆x88",
                "icon": "",
                "taskOps": 2,
                "finishNum": 2,
                "taskStatus": 2,
                "taskLogId": 890832,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x88",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/A4/CmcEHVvGoD-AB4ifAAAnLRUgJOQ099.png",
                "taskDescShow": "任务线一1.2",
                "awardsNum": 88,
                "taskType": 8,
                "subTask": "",
                "preTask": 246,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 2
                },
                {
                "taskId": 248,
                "taskName": "任务线一1.3",
                "gameType": 12,
                "taskDesc": "任务线一1.3188金叶子",
                "icon": "",
                "taskOps": 3,
                "finishNum": 3,
                "taskStatus": 2,
                "taskLogId": 890843,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "188金叶子",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0E/3F/CmcEHFvOh6WAXE4PAAAi8QULDxM114.png",
                "taskDescShow": "任务线一1.3",
                "awardsNum": 0,
                "taskType": 8,
                "subTask": "",
                "preTask": 247,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 3
                }
                ],
                "subListB": [
                {
                "taskId": 249,
                "taskName": "任务线一2.1",
                "gameType": 12,
                "taskDesc": "任务线一2.120000金叶子",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 0,
                "taskLogId": 890833,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "20000金叶子",
                "url": "/crush/",
                "awardsImage": "",
                "taskDescShow": "任务线一2.1",
                "awardsNum": 0,
                "taskType": 9,
                "subTask": "",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 1
                },
                {
                "taskId": 250,
                "taskName": "任务线一2.2",
                "gameType": 12,
                "taskDesc": "任务线一2.2888金叶子",
                "icon": "",
                "taskOps": 2,
                "finishNum": 2,
                "taskStatus": 2,
                "taskLogId": 890844,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "888金叶子",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/cdn/platform/task/festival/sj-leaf.png",
                "taskDescShow": "任务线一2.2",
                "awardsNum": 0,
                "taskType": 9,
                "subTask": "",
                "preTask": 249,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 2
                }
                ]
                },
                {
                "parentTask": {
                "taskId": 254,
                "taskName": "任务线二3.1",
                "gameType": 0,
                "taskDesc": "任务线二3.1伊豆x50",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 1,
                "taskLogId": 890826,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x50",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/49/CmcEHVvAR9aAdR4DAAAnLRUgJOQ264.png",
                "taskDescShow": "任务线二3.1",
                "awardsNum": 50,
                "taskType": 10,
                "subTask": "252,253",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 21,
                "sort": 3
                },
                "subListA": [
                {
                "taskId": 252,
                "taskName": "任务线二1.1",
                "gameType": 12,
                "taskDesc": "任务线二1.1伊豆x188",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 2,
                "taskLogId": 890846,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x188",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/A4/CmcEHVvGoByAX5nmAAAnLRUgJOQ473.png",
                "taskDescShow": "任务线二1.1",
                "awardsNum": 188,
                "taskType": 8,
                "subTask": "",
                "preTask": 251,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 1
                }
                ],
                "subListB": [
                {
                "taskId": 253,
                "taskName": "任务线二2.1",
                "gameType": 12,
                "taskDesc": "任务线二2.1伊豆x188",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 0,
                "taskLogId": 890848,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x188",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/A4/CmcEHVvGoByAX5nmAAAnLRUgJOQ473.png",
                "taskDescShow": "任务线二2.1",
                "awardsNum": 188,
                "taskType": 9,
                "subTask": "",
                "preTask": 251,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 2
                }
                ]
                },
                {
                "parentTask": {
                "taskId": 257,
                "taskName": "任务线三3.1",
                "gameType": 0,
                "taskDesc": "任务线三3.1伊豆x388",
                "icon": "",
                "taskOps": 1,
                "finishNum": 0,
                "taskStatus": 1,
                "taskLogId": 890827,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x388",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/49/CmcEHVvAR8CAC6S7AAAnLRUgJOQ948.png",
                "taskDescShow": "任务线三3.1",
                "awardsNum": 388,
                "taskType": 10,
                "subTask": "255,256",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 21,
                "sort": 3
                },
                "subListA": [
                {
                "taskId": 255,
                "taskName": "任务线三1.1",
                "gameType": 12,
                "taskDesc": "任务线三1.1伊豆x388",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 0,
                "taskLogId": 890853,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x388",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/49/CmcEHVvAR8CAC6S7AAAnLRUgJOQ948.png",
                "taskDescShow": "任务线三1.1",
                "awardsNum": 388,
                "taskType": 8,
                "subTask": "",
                "preTask": 254,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 1
                }
                ],
                "subListB": [
                {
                "taskId": 256,
                "taskName": "任务线三2.1",
                "gameType": 12,
                "taskDesc": "任务线三2.1伊豆x188",
                "icon": "",
                "taskOps": 1,
                "finishNum": 1,
                "taskStatus": 0,
                "taskLogId": 890850,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x188",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/A4/CmcEHVvGoByAX5nmAAAnLRUgJOQ473.png",
                "taskDescShow": "任务线三2.1",
                "awardsNum": 188,
                "taskType": 9,
                "subTask": "",
                "preTask": 254,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 2
                }
                ]
                },
                {
                "parentTask": {
                "taskId": 260,
                "taskName": "任务线四3.1",
                "gameType": 0,
                "taskDesc": "任务线四3.1伊豆x888",
                "icon": "",
                "taskOps": 1,
                "finishNum": 0,
                "taskStatus": 1,
                "taskLogId": 890859,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x888",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/49/CmcEHVvAR8CAC6S7AAAnLRUgJOQ948.png",
                "taskDescShow": "任务线四3.1",
                "awardsNum": 888,
                "taskType": 10,
                "subTask": "258,259",
                "preTask": null,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 21,
                "sort": 3
                },
                "subListA": [
                {
                "taskId": 258,
                "taskName": "任务线四1.1",
                "gameType": 12,
                "taskDesc": "任务线四1.1伊豆x388",
                "icon": "",
                "taskOps": 1,
                "finishNum": 0,
                "taskStatus": 1,
                "taskLogId": 890855,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "伊豆x388",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0C/49/CmcEHVvAR8CAC6S7AAAnLRUgJOQ948.png",
                "taskDescShow": "任务线四1.1",
                "awardsNum": 388,
                "taskType": 8,
                "subTask": "",
                "preTask": 257,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 1
                }
                ],
                "subListB": [
                {
                "taskId": 259,
                "taskName": "任务线四2.1",
                "gameType": 12,
                "taskDesc": "任务线四2.188金叶子",
                "icon": "",
                "taskOps": 1,
                "finishNum": 0,
                "taskStatus": 1,
                "taskLogId": 890857,
                "cycle": 1,
                "awardsType": 1,
                "awardsName": "88金叶子",
                "url": "/crush/",
                "awardsImage": "https://file.beeplay123.com/group1/M00/0E/3F/CmcEHFvOiYKAT99SAAAi8QULDxM122.png",
                "taskDescShow": "任务线四2.1",
                "awardsNum": 0,
                "taskType": 9,
                "subTask": "",
                "preTask": 257,
                "startDate": "12月13日",
                "endDate": "12月13日",
                "action": 1,
                "sort": 2
                }
                ]
            }
            ],
            "totalTask": 15,
            "hasFinishedTask": 8
        }
    }
}