<template>
  <div class="profit-container" :class="{full:isFull}">
    <div v-if="!isLoading" class="profit-inner-container">
      <h4 v-if="isFull" class="p-time"
          style="font-size:.3rem;font-weight:bold;color:rgba(155,66,1,1);margin-bottom: .32rem"></h4>
      <div class="profit-items">
        <div class="p-header">
          锦鲤名单
        </div>
        <div class="p-time" style="margin-bottom: .08rem;margin-top: 0.11rem;"></div>
        <div class="p-items p-items-content" :class="{isfull:isFull}">
          <ul style="margin: .2rem;font-size: .28rem;">
            <li>
              <span style="border-right: 1px solid #fff;">序号</span>
              <span style="border-right: 1px solid #fff;">玩家昵称</span>
              <span style="border-right: 1px solid #fff;">锦鲤分类</span>
              <span>奖品</span>
            </li>
          </ul>
          <div class="p-container" :class="{isfull:isFull}">
            <scroll :data="behindThreeData" ref="scroll" :listenScroll="true" :probeType="3">
              <ul class="p-item-title">
                <li v-for="(item,index) in behindThreeData">
                  <span><i class="icon-dot">{{index+1}}</i></span>
                  <span><em class="i-ellipsis">{{item.nickName || '暂无昵称'}}</em></span>
                  <span><em class="i-ellipsis">{{item.koiName}}</em></span>
                  <span><em class="i-ellipsis">{{item.awardName}}</em></span>
                </li>
                <li v-if="isOpen" v-for="(item,index) in otherData">
                  <span><i class="icon-dot">{{index+behindThreeData.length+1}}</i></span>
                  <span><em class="i-ellipsis">{{item.nickName || '暂无昵称'}}</em></span>
                  <span><em class="i-ellipsis">{{item.koiName}}</em></span>
                  <span><em class="i-ellipsis">{{item.awardName}}</em></span>
                </li>
                <li v-if="!isOpen">
                  <a href="javascript:" class="btn-check-profit" @click.stop="closeOpenProfit"></a>
                </li>
                <li v-for="(item,index) in lastThreeData">
                  <span><i class="icon-dot">{{index+behindThreeData.length+otherData.length+1}}</i></span>
                  <span><em class="i-ellipsis">{{item.nickName || '暂无昵称'}}</em></span>
                  <span><em class="i-ellipsis">{{item.koiName}}</em></span>
                  <span><em class="i-ellipsis">{{item.awardName}}</em></span>
                </li>
              </ul>
            </scroll>
          </div>
        </div>
      </div>
      <!--<div class="profit-footer">仅50名及以内有奖励</div>-->
    </div>
    <div class="loading-wrap" v-if="isLoading">
      <div class="container">
        <div class="spinner">
          <div class="bar1"></div>
          <div class="bar2"></div>
          <div class="bar3"></div>
          <div class="bar4"></div>
          <div class="bar5"></div>
          <div class="bar6"></div>
          <div class="bar7"></div>
          <div class="bar8"></div>
          <div class="bar9"></div>
          <div class="bar10"></div>
          <div class="bar11"></div>
          <div class="bar12"></div>
        </div>
      </div>
    </div>
  </div>
</template>
<script type="text/javascript">
  import rule from '../../../components/rule'
  import {rankList, activityInfo, userRanking} from '../../../utils/api'

  export default {
    data() {
      return {
        curIndex: 0,
        profitData: [],
        topthreeData: [],
        behindThreeData: [],
        otherData: [],
        lastThreeData: [],
        isOpen: true,
        countTime: null,
        endTime: '',
        myInfo: {},
        isLoading: false,
        defaultImg: '/cdn/common/images/common/img_photo.png'
      }
    },
    props: {
      isFull: {
        type: Boolean,
        default: false
      },
      from: {
        type: Number,
        default: 0
      }
    },
    components: {
      rule: () => import('../../../components/rule'),
      scroll: () => import('../../../components/scroll')
    },
    mounted() {
      this.getRankList()
      this.getActivityInfo()
    },
    methods: {
      closeOpenProfit() {
        this.isOpen = true
        setTimeout(() => {
          this.$refs.scroll.scrollTo(0, 0)// 滑到顶部
          this.$refs.scroll && this.$refs.scroll.refresh()
        })
      },
      async getRankList() {
        // this.isLoading = true
        // const {code, data} = await rankList()
        // if (code === 200) {
        let data=[{
          "userId": null,
          "channelId": null,
          "nickName": "大M****89",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "龍哥****24",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "还要****梦想",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "游戏****达人",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****70",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****34",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****25",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "18****01",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****54",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****34",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****83",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "所谓****我看",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "汤姆****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "铁西****东哥",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "星辉****风沙",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****12",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****02",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "星宝****星宝",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "y恨****死了",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****91",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "15****60",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****22",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****14",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "股票****竞价",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "18****89",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****21",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****11",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****08",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "加油****吉味",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "18****25",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "浩携****携戍",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "19****70",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "好运****十足",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****04",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****24",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****21",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****42",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "说什****什么",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "*帝****19",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "兹似****诘簇",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****65",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****54",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****82",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "15****16",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****51",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "85****63",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "18****98",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13****93",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "wu****60",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "相公****官人",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****43",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "黄鹏****思宇",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****32",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****22",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "呵呵****呵呵",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****01",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "qt****bs",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "农民****城来",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****20",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****04",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****34",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "把你****融化",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "嚯嚯****嚯够",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****92",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "，****",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "赤雨****赤雨",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "ti****05",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "yo****an",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****50",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****64",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****91",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "金h****3_",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "et****va",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "迷路****精灵",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "拍的****吐雪",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****63",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "光明****光明",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****02",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "禄****",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "ZQ****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****63",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****31",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****91",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "稳稳****稳稳",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****80",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "朱总****多多",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****71",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****60",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****07",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****52",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****73",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****64",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "re****01",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****74",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "军书****无名",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****90",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****61",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****84",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "范荣****范荣",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****20",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****01",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****93",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "给我****我砸",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "72****快乐",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "银子****有a",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****00",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "17****53",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****12",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****01",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****43",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13****97",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "失心****迷途",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****43",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13******",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "真我****自由",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "jd****42",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****84",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "18****76",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "ZQ****54",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****21",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****53",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****61",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "Mi****iy",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****53",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****40",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****71",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "清枫****神竹",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****44",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "裕佳****少雄",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "迪福****79",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****74",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****22",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "冰姬****玉雪",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "13****79",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****73",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****72",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "aa****03",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "re****43",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "自在****遨游",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****42",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "迷糊****正太",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****54",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****10",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****63",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****63",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****62",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "xl****53",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "90****ei",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****42",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****81",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****14",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "17****27",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "罗蛮****蛮蛮",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "风吹****山岗",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "Tr****es",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****80",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****10",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "橙锦鲤",
          "awardName": "铜套圈X1",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "煎饼****大果",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****53",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****39",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****82",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****94",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "fo****s山",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****06",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****50",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****48",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****66",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "lu****最正",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****85",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****83",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****54",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****34",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "都i****i万",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****61",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****30",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****67",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****18",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "木听****听蜂",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****32",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****72",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****78",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****11",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "云南****科科",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****75",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****03",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****67",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****19",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "改革****字南",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****55",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****50",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****13",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****95",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "咿咿****呀我",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****36",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****27",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****19",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****25",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "想入****霏╮",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****02",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****94",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****36",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****75",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "来个****奖池",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****65",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****41",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****68",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****00",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "大洋****洋芋",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****26",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****24",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****03",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****92",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "香水****五度",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****65",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****80",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****95",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****90",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "筱筱****筱桂",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****22",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****45",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****20",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****08",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "来几****个鱼",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****18",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****22",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****88",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****94",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "赤角****大现",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****49",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****01",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****81",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****12",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "湾崽****唛头",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****44",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****69",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****87",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****26",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "币重****吧百",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****14",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****22",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****49",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****27",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "四壁****出哥",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****20",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****93",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****31",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****01",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "kk****洋洋",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****74",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****94",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****78",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****41",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "熊f****ff",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****61",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****51",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****08",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****13",
          "koiName": "蓝锦鲤",
          "awardName": "1000金叶子",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****11",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****20",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****63",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****47",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****39",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "y****to",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****37",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****10",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****07",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****05",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****18",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****99",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****25",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****46",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****19",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****64",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****84",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****00",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****74",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****46",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****12",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****17",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****62",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****82",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****78",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****89",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****06",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****33",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****54",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****77",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****10",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****09",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****32",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****78",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****80",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****87",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****92",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****26",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****36",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****98",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "赢****",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****14",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****14",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****27",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****60",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****39",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****75",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****18",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****44",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****73",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "大****白",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****77",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****70",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****77",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****26",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****57",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****39",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****24",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****02",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****17",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****79",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****73",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****71",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****66",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****95",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****18",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****64",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****86",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****80",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****19",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****63",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****33",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****07",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****28",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****06",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "海蓝****心",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****35",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****06",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****72",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****26",
          "koiName": "白锦鲤",
          "awardName": "50元话费",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****88",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****43",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****69",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****94",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****93",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "su****mi",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****91",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****18",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****17",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****66",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****42",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****96",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****90",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****91",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****28",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****26",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****20",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****51",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****34",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****34",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****68",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****61",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****43",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****83",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****56",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****22",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****71",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****83",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****60",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****10",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****16",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****79",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****95",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****78",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "小****儿",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****46",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****63",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****35",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****28",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****99",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****80",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****65",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****98",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****36",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "你****得",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****91",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****33",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****66",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****67",
          "koiName": "绿锦鲤",
          "awardName": "100元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****34",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****91",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****46",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****36",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****47",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****81",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****60",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****49",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****11",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****30",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "Ye****s",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****91",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****43",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****66",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****05",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "ss****s",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****48",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****29",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****12",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "bd****23",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****38",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****42",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****56",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****44",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****09",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****13",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****80",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****92",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****43",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****94",
          "koiName": "红锦鲤",
          "awardName": "500元话费券",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****15",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****20",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "MZ****74",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****07",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****46",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****55",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****28",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****92",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "YK****83",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }, {
          "userId": null,
          "channelId": null,
          "nickName": "hk****76",
          "koiName": "紫锦鲤",
          "awardName": "888元京东卡",
          "awardId": null
        }];
          this.profitData = data
          this.isOpen = false
          this.lastThreeData = this.profitData.slice(this.profitData.length - 6)
          this.behindThreeData = this.profitData.slice(0, 6)
          this.otherData = this.profitData.slice(6, this.profitData.length - 6)
          this.isLoading = false
        // }
      },
      async getActivityInfo() {
        const {code, data} = await activityInfo()
        if (code === 200) {
          this.endTime = data.endDate
        }
      },
      async getUserRanking() {
        const {code, data} = await userRanking()
        if (code === 200) {
          this.myInfo = data
          if (this.isFull) {
            this.$emit('set-my-info', data)
          }
        }
      },
      countDown(item) {
        if (!item) return false
        let date = item / 1000
        this.timer = setInterval(() => {
          date = date - 1
          if (date <= 0) {
            date = 0
            clearInterval(this.timer)
          }
          let day = Math.floor(date / 86400)
          let hour = Math.floor(parseInt(date / 60 / 60) % 24)
          let minute = Math.floor(parseInt(date / 60) % 60)
          let second = Math.floor(date % 60)
          // let countDay = day >= 10 ? day : '0' + day
          let countHour = hour >= 10 ? hour : '0' + hour
          let countMinute = minute >= 10 ? minute : '0' + minute
          let countSecond = second >= 10 ? second : '0' + second
          if (day >= 2) {
            this.countTime = 0
          } else if (day > 0) {
            this.countTime = `${day}天${countHour}:${countMinute}:${countSecond}`
          } else {
            this.countTime = `${countHour}:${countMinute}:${countSecond}`
          }
        }, 1000)
      }
    }
  }
</script>
<style lang="less" scoped>
  @import "./index.less";

  .loading-wrap {
    // position: fixed;
    // top: 0;
    // left: 0;
    // width: 100%;
    // height: 100%;
    // background-color: rgba(0, 0, 0, 0);
    // z-index: 15;
  }

  .container {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 0.8rem;
    height: 0.8rem;
    border-radius: 10%;
  }

  .spinner {
    height: 100%;
    width: 100%;
    position: relative;
    margin: 0 auto;
  }

  .spinner div {
    width: 10%;
    height: 26%;
    background-color: #e2812a;
    position: absolute;
    left: 44.5%;
    top: 37%;
    opacity: 0;
    border-radius: 30%;
    animation: fade 1s linear infinite;
  }

  .spinner div.bar1 {
    transform: rotate(0deg) translate(0, -142%);
    animation-delay: 0s;
  }

  .spinner div.bar2 {
    transform: rotate(30deg) translate(0, -142%);
    animation-delay: -0.9167s;
  }

  .spinner div.bar3 {
    transform: rotate(60deg) translate(0, -142%);
    animation-delay: -0.833s;
  }

  .spinner div.bar4 {
    transform: rotate(90deg) translate(0, -142%);
    animation-delay: -0.75s;
  }

  .spinner div.bar5 {
    transform: rotate(120deg) translate(0, -142%);
    animation-delay: -0.667s;
  }

  .spinner div.bar6 {
    transform: rotate(150deg) translate(0, -142%);
    animation-delay: -0.5833s;
  }

  .spinner div.bar7 {
    transform: rotate(180deg) translate(0, -142%);
    animation-delay: -0.5s;
  }

  .spinner div.bar8 {
    transform: rotate(210deg) translate(0, -142%);
    animation-delay: -0.41667s;
  }

  .spinner div.bar9 {
    transform: rotate(240deg) translate(0, -142%);
    animation-delay: -0.333s;
  }

  .spinner div.bar10 {
    transform: rotate(270deg) translate(0, -142%);
    animation-delay: -0.25s;
  }

  .spinner div.bar11 {
    transform: rotate(300deg) translate(0, -142%);
    animation-delay: -0.1667s;
  }

  .spinner div.bar12 {
    transform: rotate(330deg) translate(0, -142%);
    animation-delay: -0.0833s;
  }

  @keyframes fade {
    from {
      opacity: 0.8;
    }
    to {
      opacity: 0.25;
    }
  }
</style>
